### ISSUE TITLE
bug when running commit cmd

### ISSUE THREAD

**Issue by mootezbessifi** [abessifi/pyatta#7] opened 2014-04-22 13:22 UTC
when you try to commit some new added configs and something wrong happened, -run() method in utils.py have to rise an exception and executes the following lines:
except subprocess.CalledProcessError:
            out = False
logger.debug('command output: %s', out)
return ' '.join(out.splitlines())

in this case "out" is a boolean variable that doesn't have splitelines as appropriate method

**Comment by abessifi** [comment] 2014-04-27 11:06
Thanks for reporting the bug.
The issue is now fixed :
https://github.com/vaytess/pyatta/commit/92c8feb44a7f22e25c3a20d15125d1398b2da6eb
You can pull and run tests/test_config_session.py unittests to be sure ;)

**Closed as completed by abessifi** 2014-04-27 11:06 UTC
Labels: bug
